apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argus-web
spec:
  ingressClassName: nginx
  rules:
    - host: argus.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argus-web
                port:
                  number: 80
