apiVersion: v1
kind: Service
metadata:
  name: argus-web
spec:
  type: {{ .Values.service.type }}
  selector:
    app: argus-web
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
